name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Linters
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy python3-pip
          pip3 install flake8

      - name: Lint C++
        run: |
          # This is a placeholder; adjust globbing as needed
          find src -name "*.cpp" | xargs clang-tidy -- -I./src

      - name: Lint Python
        run: flake8 python/
